basePath: /
definitions:
  helpers.APIError:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  helpers.LoginInput:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  helpers.LoginResponse:
    properties:
      token:
        type: string
    type: object
  helpers.RegisterInput:
    properties:
      age:
        type: integer
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  helpers.RegisterResponse:
    properties:
      age:
        type: integer
      email:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: soberkoder@swagger.io
    name: API Support
  description: This is a sample service for managing cars
  termsOfService: http://swagger.io/terms/
  title: MyGram API
  version: "1.0"
paths:
  /users/login:
    post:
      parameters:
      - description: User Login
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/helpers.LoginInput'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.APIError'
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/helpers.APIError'
      summary: login a user
      tags:
      - Users
  /users/register:
    post:
      parameters:
      - description: User Register
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/helpers.RegisterInput'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/helpers.RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.APIError'
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/helpers.APIError'
      summary: create a user
      tags:
      - Users
swagger: "2.0"
